version: '3'

services:
  db:
    build:
      context: "./MySQL"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    container_name: golang_db
    ports:
      - "3306:3306"
    tty: true
    volumes:
      - "./_data:/var/lib/mysql"
  app:
    build:
      context: "./Go"
    volumes:
      - "./Go:/go"
    container_name: golang_app
    restart: always
    ports:
      - "8082:8080"
    tty: true
    depends_on:
      - db